---
directories:
  "app/controllers":
    TooManyInstanceVariables:
      enabled: false

  "app/jobs":
    UtilityFunction:
      enabled: false

detectors:
  Attribute:
    enabled: false

  IrresponsibleModule:
    enabled: false

  InstanceVariableAssumption:
    enabled: false

  NilCheck:
    enabled: false

  DuplicateMethodCall:
    enabled: false

  ControlParameter:
    enabled: false

  TooManyStatements:
    enabled: false

  TooManyConstants:
    enabled: false

  LongParameterList:
    enabled: true
    max_params: 4

  TooManyInstanceVariables:
    max_instance_variables: 7

  UtilityFunction:
    public_methods_only: true

  NestedIterators:
    enabled: true
    max_allowed_nesting: 3
      