version: '3.8'
services:
  db:
    container_name: app_postgres
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=uluru
      - POSTGRES_PASSWORD=uluru123
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - "5432:5432"
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
  redis:
    container_name: app_redis
    image: redis
    ports:
      - 6379:6379

